### ISSUE TITLE
Copied to plugins folder and get error

### ISSUE THREAD

**Issue by kharder69** [argp/iBoot64helper#1]
---
## Warning

iBoot64helper.py: global name 'true' is not defined
Traceback (most recent call last):
  File "C:\Program Files (x86)\IDA 6.8\python\idaapi.py", line 541, in IDAPython_ExecScript
    execfile(script, g)
  File "C:/Program Files (x86)/IDA 6.8/plugins/iBoot64helper.py", line 51, in <module>
    main()
  File "C:/Program Files (x86)/IDA 6.8/plugins/iBoot64helper.py", line 13, in main
    while(true):
NameError: global name 'true' is not defined

---

**Comment by argp** [comment]
Weird, try now.

**Comment by kharder69** [comment]
Trying it now.  Startup of IDA now is not coming up but see process running at 30% CPU utilization.  Will let it run for a bit and see what happens.

**Comment by kharder69** [comment]
IDA process just keeps running around 30 - 40 % CPU utilization but now window appears.  Weird.

**Comment by argp** [comment]
What are you trying it on? This is supposed to be used on an iBoot ARM64 image.
